### ISSUE TITLE
stream-deck-fritz does not work since update to Fritz!OS 7.27

### ISSUE THREAD

**Issue by mskranz** [heutelbeck/streamdeck-fritz#1]
Hi.
I would love to help identifying and fixing the root cause. Just wanted to double check whether you have any ideas?
Cheers!

**Comment by heutelbeck** [comment]
Well, first off I am happy that this project got some use. Other than that, I have no idea. I am still on 7.22, and as my Fritz is owned by the provider, I cannot update, test, and reproduce.  I took a quick look at the API documents of AVM: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf and I do not see something obvious that could have changed.

**Comment by mskranz** [comment]
Cool, thanks for the quick follow-up.
Well, something has indeed changed. Everytime I now hit the Stream Deck button, I can see that the authentication failed due to wrong password. I have not changed password though and also with a new user with a fresh password it is still the same (wrong) error message.

**Comment by mskranz** [comment]
Here we go, I think I found something interesting on the AVM home page.

> Important: Change to FRITZ!Box login process
> 
> Starting with FRITZ!OS 7.25, there is a change when logging in with the FRITZ!Box password, which app developers will need to take into account. The change is also part of the FRITZ!OS 7.24 Lab version.
> 
> The document below describes the changes and provides recommendations for user guidance for logging into a FRITZ!Box. 

> The document is intended for developers who program third-party applications for FRITZ!Box. From a usability point of view, developers of third-party applications are strongly recommended to adapt their user interface and terms to the behavior of the FRITZ!Box interface, which is familiar to the user

[Changes (PDF)](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/Recommendations%20for%20user%20guidance%20for%20logging%20into%20a%20FRITZBox_v1.1_EN.pdf)

**Comment by ToemD** [comment]
Because of the change in FRITZ!OS an username is required for getting the SID.
I'm new to this project, so I didn't want to change the source code directly.
You're welcome to integrate my changes.

Here my new function authnAndExecute to fix this and I also added the parameters address to the function executeCommand to get an individual FRITZ!Box-Address to work:
```
function authnAndExecute(address, username, password, command, ain, parameters, callback) {
	var baseUrl = 'http://'+address+'/login_sid.lua';
	var url = baseUrl;
	if(username) {
		url+= '?username='+username;
	}
	httpGetAsync(url, 
		function (challengeData) {
			var parser = new DOMParser();
			var xmlDoc = parser.parseFromString(challengeData, "text/xml");
			var sid = xmlDoc.getElementsByTagName("SID")[0].childNodes[0].nodeValue;
			if(isInvalidSID(sid)) {
				var challenge = xmlDoc.getElementsByTagName("Challenge")[0].childNodes[0].nodeValue;
				var response = challenge+"-"+MD5(challenge+'-'+password);
				if(username) {
					response+= '&username='+username;
				}	
				var result = httpGetAsync(baseUrl+'?response='+response,
					function(authnResponse) {
						var authnXmlDoc = parser.parseFromString(authnResponse, "text/xml");
						var theRealSid = authnXmlDoc.getElementsByTagName("SID")[0].childNodes[0].nodeValue;
						executeCommand(address,command,ain,theRealSid,parameters,callback);
					}
				); 				
			} else {
				executeCommand(address,command,ain,sid,parameters,callback);
			}
		}
	);
}
function executeCommand (address,command, ain, sid, parameters, callback) {
	var url = 'http://'+address+'/webservices/homeautoswitch.lua';
	url += '?ain='+ain+'&switchcmd='+command+'&sid='+sid;
	if(parameters) {
		url += '&param='+parameters;
	}
	var result = httpGetAsync(url, function (response)
		{
			if(callback) {
				callback(response);
			}
		}); 
}
```

**Comment by ghost** [comment]
@ToemD , i can confirm, works like a charm - Good work and thx a lot :)

**Comment by heutelbeck** [comment]
@ToemD thank you for the patch. I missed your original message. Thanks to @DarealAL I discovered it. I incorporated the fix accordingly, and I can confirm, that it now works again with FRITZ!OS 07.29.
Feel free to send pull requests for further improvements. I currently do not have the plugin in active use myself.

Again thank you. Version 0.2 is now pushed.
